# Ghostty terminal; the `noctalia` theme file itself is generated at runtime (unmanaged).
{ ... }:
{
  flake.modules.homeManager.ghostty =
    { ... }:
    {
      programs.ghostty = {
        enable = true;
        enableZshIntegration = true;
        installBatSyntax = true;
        settings = {
          # Font
          font-size = 12;

          # Window
          window-decoration = false;
          window-padding-x = 12;
          window-padding-y = 12;
          background-opacity = "1.0";
          background-blur = 32;

          # Cursor
          cursor-style = "block";
          cursor-style-blink = true;

          # Scrollback
          scrollback-limit = 3023;

          # Terminal features
          mouse-hide-while-typing = true;
          copy-on-select = false;
          confirm-close-surface = false;
          app-notifications = "no-clipboard-copy,no-config-reload";

          keybind = [
            "ctrl+shift+n=new_window"
            "ctrl+t=new_tab"
            "ctrl+plus=increase_font_size:1"
            "ctrl+minus=decrease_font_size:1"
            "ctrl+zero=reset_font_size"
            "shift+enter=text:\\n"
          ];

          # Splits
          unfocused-split-opacity = "0.7";
          unfocused-split-fill = "#44464f";

          # Tabs / GTK
          gtk-titlebar = false;
          gtk-single-instance = true;

          # Shell integration
          shell-integration = "detect";
          shell-integration-features = "cursor,sudo,title,no-cursor";

          # Generated by noctalia (matugen); lives in ~/.config/ghostty/themes/noctalia
          theme = "noctalia";
        };
      };
    };
}
